import './App.css';
import { Link } from 'react-router-dom';
import DailyBugle from './images/DailyBugle.png';
import Paper from './images/paper.png';
import Enough from './images/enough.png';
import Terror from './images/terror.png';
import { useState } from 'react';

export function App() {
  return (
    <div>
      <span className='images'><img src={DailyBugle} alt="Daily Bugle Logo" /></span>
      <hr />
      <nav className='header'>
        <ul>
          <li><Link to="/" style={{ color: "red" }}>Home</Link></li>
          <li><Link to="/about">About Us</Link></li>
          <li><Link to="/menaceWatch">Menace Watch</Link></li>
          <li><Link to="/spiderSlayer">Spider Slayer Project</Link></li>
        </ul>
      </nav>
      <hr />
      <br />

      <iframe width="560" height="315" src="https://www.youtube.com/embed/6LS860xepoY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

      <br /><br />

      <h2>Past Big Story Daily Bugle Exclusives</h2>


      <span className='pastReports'>
        <img src={Paper} alt="DailyBuglePaper"/>
        <img src={Enough} alt="DailyBuglePaper"/>
        <img src="https://www.pulpinternational.com/images/postimg/along_came_a_spider_01.jpg" alt="DailyBuglePaper"/>
        <img src={Terror} alt="DailyBuglePaper"/>
      </span>

    </div >
  );
}

export function AboutUs() {
  return (
    <div>
      <span className='images'><img src={DailyBugle} alt="Daily Bugle Logo" /></span>
      <hr />
      <nav className='header'>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/about" style={{ color: "red" }}>About Us</Link></li>
          <li><Link to="/menaceWatch">Menace Watch</Link></li>
          <li><Link to="/spiderSlayer">Spider Slayer Project</Link></li>
        </ul>
      </nav>
      <hr />
      <span className="daily">
        <img src="https://donttellharrycom.files.wordpress.com/2021/02/daily-bugle-offices.jpg " alt="Exterior Daily Bugle" />

        {/* Content generated by OpenAI's GPT-3.5 model */}
        <p>Welcome to the Daily Bugle, your most trusted source for accurate, hard-hitting journalism in New York City! Established with a commitment to uphold the principles of truth, integrity, and fearless reporting, the Bugle has been serving the citizens of this great metropolis for decades. Led by our esteemed publisher, J. Jonah Jameson, we take immense pride in our relentless pursuit of the truth, exposing corruption, celebrating triumphs, and shedding light on the stories that matter most to our readers. With a team of dedicated reporters and editors, we strive to keep our fingers on the pulse of the city, delivering news that informs, educates, and empowers you, the citizens of New York, every single day.<br /><br />

          Since our inception, the Daily Bugle has earned a reputation as the go-to source for unbiased reporting, capturing the essence of life in the Big Apple and beyond. From local politics and crime investigations to culture, sports, and business, our comprehensive coverage spans a wide spectrum of topics, keeping you well-informed about the issues that impact your daily life. We take pride in our dedication to factual reporting, presenting multiple perspectives to foster thoughtful conversations and empower our readers to form their own informed opinions. At the Daily Bugle, journalism isn't just a profession; it's a mission to serve our community, and we invite you to join us on this exciting journey as we continue to be the voice of truth and justice in the city that never sleeps.</p>
      </span>

      <span className='daily'>

        {/* Content generated by OpenAI's GPT-3.5 model */}
        <p>At the heart of the Daily Bugle's unwavering commitment to journalistic excellence stands our illustrious publisher, J. Jonah Jameson. A formidable figure known for his unapologetic passion, Mr. Jameson's relentless pursuit of truth and justice has become the driving force behind our publication's success. As a seasoned newspaperman with decades of experience, his no-nonsense approach to reporting has garnered both admiration and controversy, making him a charismatic and polarizing figure in the media landscape. Beneath that gruff exterior lies a man deeply devoted to the city he calls home, a man whose determination to expose wrongdoings and hold those in power accountable has become synonymous with the Bugle's very identity. With an indomitable spirit and an unyielding dedication to the pursuit of truth, Mr. Jameson continues to lead the Daily Bugle into the future, inspiring us all to carry forth the legacy of fearless journalism that defines our storied publication.</p>
        <img src="https://sportshub.cbsistatic.com/i/2021/03/16/679c4a04-a8e3-46a5-8d1b-0fe4f6fdd1d1/spider-man-homecoming-the-daily-bugle-1011056.jpg" alt="Mr. Jameson" />
      </span>
    </div>
  );
}

export function SpiderSlayer() {
  return (
    <div>
      <span className='images'><img src={DailyBugle} alt="Daily Bugle Logo" /></span>
      <hr />

      <nav className='header'>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/about">About Us</Link></li>
          <li><Link to="/menaceWatch">Menace Watch</Link></li>
          <li><Link to="/spiderSlayer" style={{ color: "red" }}>Spider Slayer Project</Link></li>
        </ul>
      </nav>
      <hr />

      <span class="daily">
        <span class="imageBorder">
          <img src="https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Spider-Slayer-Mk1-Marvel-Comics-Spider-Man.jpg/220px-Spider-Slayer-Mk1-Marvel-Comics-Spider-Man.jpg" alt="spiderslayer" style={{ width: 200, height: 350 }} />
        </span>

        {/* Content generated by OpenAI's GPT-3.5 model */}
        <p>Ah, the dreaded Spider Slayer! This menacing contraption, my dear readers, is a testament to human ingenuity and the unwavering determination to rid our fair city of the arachnid menace that plagues our streets. As the esteemed publisher of the Daily Bugle, it is my duty to expose the truth behind this mechanical marvel. Developed by the brilliant minds at Oscorp, the Spider Slayer represents the pinnacle of cutting-edge technology designed specifically to target that vexatious web-slinging pest, Spider-Man! No longer shall we live in fear of the wall-crawling nuisance, as the Spider Slayer stands ready to deliver swift and decisive justice, striking fear into the heart of every criminal, and finally granting us the peace we so rightfully deserve.

          <br /><br />
          The Daily Bugle are proud sponsers of the Spider Slayer project and will keep you updated as progress is made to stop this so called superhero.

          <br /><br />

          J. Jonah Jameson - Editor in Cheif of The Daily Bugle</p>
      </span>
    </div >
  );
}

export function MenaceWatch() {
  const cities = ["Avoid: Harlem", "Avoid: Upper West Side", "Avoid: Central Park", "Avoid: Upper East Side", "Avoid: Midtown", "Avoid: Hell's Kitchen", "Avoid: Greenwich", "Avoid: Chinatown", "Avoid: Financial Distrect"];
  const [city, setCity] = useState();
  return (
    <div>
      <span className='images'><img src={DailyBugle} alt="Daily Bugle Logo" /></span>
      <hr />

      <nav className='header'>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/about">About Us</Link></li>
          <li><Link to="/menaceWatch" style={{ color: "red" }}>Menace Watch</Link></li>
          <li><Link to="/spiderSlayer">Spider Slayer Project</Link></li>
        </ul>
      </nav>
      <hr />

      <span class="menace">
        {/* Content generated by OpenAI's GPT-3.5 model */}
        <p className='city'>Ladies and gentlemen, allow me to introduce you to my latest brainchild: the ingenious Menace Watch! In the pursuit of journalism and delivering factual news to the citizens of New York City, I devised this remarkable tracking system that will keep a watchful eye on that elusive wall-crawling miscreant, Spider-Man while providing updates where he is for the public to avoid. Picture this – a network of state-of-the-art sensors strategically placed across our bustling metropolis, each attuned to detect the distinctive vibrations caused by Spider-Man's acrobatics and web-slinging escapades.

          <br /><br />

          With the Menace Watch at our disposal, we can finally shed light on the elusive movements of this so-called "friendly neighborhood" menace. No more rumors, no more wild speculations – just concrete evidence of Spider-Man's whereabouts, ensuring that we report the truth to our readers. Imagine the headlines: "Spider-Man Spotted Swinging Across Queens!" or "Wall-Crawler Caught Foiling a Robbery in Progress!" The citizens of New York City deserve to know the real story, and the Menace Watch shall be the instrument that delivers it to them with unwavering accuracy.

          <br /><br />

          Of course, some naysayers might cry foul, citing privacy concerns or accusing me of being overly obsessed with unmasking the webbed wonder. But let me assure you, dear readers, my intentions are purely altruistic. With great power comes great responsibility, and it is my duty as the esteemed publisher of the Daily Bugle to provide transparency and expose any potential threats, even those hiding behind a red and blue mask. The Menace Watch shall become the beacon of truth, guiding us toward a safer city, free from the shadows cast by Spider-Man's secretive antics. So, let the skeptics scoff and the critics critique – for soon, the Menace Watch will weave its web of revelation, and the citizens of New York will finally know the truth behind the enigmatic figure that haunts our city's skyline.

          <br /><br />

          J. Jonah Jameson - Editor in Cheif of The Daily Bugle</p>
      </span>

      <span className='location'>
        <button onClick={() => {
          setCity(Math.floor(Math.random() * 9));
        }}>Get Location</button>
      </span>

      <p className="city">{cities[city]}</p>
    </div>
  );
}